#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight)
#pragma config(Motor,  motor3,          armMotor,      tmotorVexIQ, openLoop)
#pragma config(Motor,  motor4,          clawMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1 == 1)
	{
		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];
	}

	if(vexRT[Btn6U] == 1)
	{
		motor[armMotor] = 100;
	}
	else if(vexRT[Btn6D] == 1)
	{
		motor[armMotor] = -100;
	}
	else
	{
		motor[armMotor] = 0;
	}

	if(vexRT[Btn5U] == 1)
	{
		motor[clawMotor] = 100;
	}
	else if(vexRT[Btn5D] == 1)
	{
		motor[clawMotor] = -100;
	}
	else
	{
		motor[clawMotor] = 0;
	}

}
